services:
  - type: web
    name: tic-tac-toe-server
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
    plan: free 